library(tidyverse)
aUtoMobile<-read.csv("C:/Users/saic3/CSE3046-F2-LAB_SLOT_L3+L4/Datasets/Automobile.csv")
View(aUtoMobile)
count(aUtoMobile["price">14000])
aUtoMobile%>%group_by(company)%>%summarise(count=n())
count(aUtoMobile%>%filter(price<14000))
count()
count(aUtoMobile%>%filter(body.style=="sedan"))
aUtoMobile%>%group_by(company)%>%summarise(expensive=max(price,na.rm = T))
aUtoMobile%>%filter(company=="toyota")
head(aUtoMobile)
count(
  aUtoMobile%>%filter(company=="alfa-romero",body.style=="convertible")
  )
